title: Your awesome title
author:
  name: Rouven Bissinger
  email: contact@rouvenbissinger.com

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/hedg3hog/hedg3hog" }
plugins:
- jekyll-remote-theme 

feed:
  disable: true